# Generated by Django 6.0.2 on 2026-02-06 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_role_userrole"),
    ]

    operations = [
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., National President", max_length=100
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("national", "National"),
                            ("state", "State"),
                            ("district", "District"),
                            ("mandal", "Mandal"),
                            ("college", "College"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Social Media, Press, IT Cell, Legal",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Short summary of the role", null=True
                    ),
                ),
                (
                    "responsibilities",
                    models.TextField(help_text="List of responsibilities"),
                ),
                ("authority", models.TextField(help_text="Authority and powers")),
                (
                    "accountability",
                    models.TextField(help_text="Accountability and duties"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent designation for hierarchy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="accounts.designation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Designation",
                "verbose_name_plural": "Designations",
                "ordering": ["level", "name"],
            },
        ),
    ]
