# Generated by Django 6.0.2 on 2026-02-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
