# Generated by Django 6.0.2 on 2026-02-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="photo_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
